version: 2

jobs:
  build:
    working_directory: ~/voter-engagement

    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgres://circleci:@127.0.0.1:5432/voterengagement_test
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          - POSTGRES_USER=circleci
          - POSTGRES_DB=voterengagement_test

    steps:
      - checkout

      - run:
          name: Installing Node and Yarn
          command: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update && sudo apt-get install -y nodejs yarn

      - run:
          name: Checking system dependencies
          command: make doctor

      - type: cache-restore
        key: pipenv-{{ checksum "Pipfile.lock" }}
      - type: cache-restore
        key: yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Installing project dependencies
          command: make install

      - type: cache-save
        key: pipenv-{{ checksum "Pipfile.lock" }}
        paths:
          - .venv
      - type: cache-save
        key: yarn-{{ checksum "yarn.lock" }}
        paths:
          - node_modules

      - run:
          name: Checking backend code
          command: make check-backend

      - run:
          name: Running backend tests
          command: make test-backend

      - run:
          name: Running frontend tests
          command: make test-frontend
