# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.City'),
        ),
        migrations.AlterField(
            model_name='region',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.County'),
        ),
        migrations.AlterField(
            model_name='region',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.Ward'),
        ),
    ]
