# Generated by Django 2.0 on 2017-12-06 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_blank_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='elections.City'),
        ),
        migrations.AlterField(
            model_name='region',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='elections.County'),
        ),
        migrations.AlterField(
            model_name='region',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='elections.Ward'),
        ),
    ]
