# Generated by Django 2.0.6 on 2018-07-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_auto_20180103_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='email_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
