# Generated by Django 2.0 on 2017-12-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_voter_regions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
